//! Blocking HTTP client for Abyss terminal SSO endpoints.

use chrono::{DateTime, Utc};
use reqwest::{Url, blocking::Client};
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use uuid::Uuid;

use crate::{error::TerminalAuthError, session::AuthenticatedUser};

const TERMINAL_START_PATH: &str = "auth/terminal/start";
const TERMINAL_POLL_PATH: &str = "auth/terminal/poll";
const TERMINAL_EXCHANGE_PATH: &str = "auth/terminal/exchange";
const NATIVE_ME_PATH: &str = "auth/native/me";
const NATIVE_LOGOUT_PATH: &str = "auth/native/logout";

/// Blocking client contract for the control-plane authentication endpoints.
pub trait ControlPlaneAuthClient {
    /// Creates a new terminal login attempt.
    ///
    /// # Errors
    ///
    /// Returns an error when the control-plane request fails, returns a
    /// non-success status, or responds with an unexpected JSON body.
    fn start_terminal_login(
        &self,
        request: &TerminalStartRequest,
    ) -> Result<TerminalStartResponse, TerminalAuthError>;

    /// Polls a terminal login attempt for completion.
    ///
    /// # Errors
    ///
    /// Returns an error when the control-plane request fails, returns a
    /// non-success status, or responds with an unexpected JSON body.
    fn poll_terminal_login(
        &self,
        request: &TerminalPollRequest,
    ) -> Result<TerminalPollResponse, TerminalAuthError>;

    /// Exchanges a completed terminal login attempt for a native bearer token.
    ///
    /// # Errors
    ///
    /// Returns an error when the control-plane request fails, returns a
    /// non-success status, rejects the verifier, or responds with an
    /// unexpected JSON body.
    fn exchange_terminal_login(
        &self,
        request: &TerminalExchangeRequest,
    ) -> Result<TerminalExchangeResponse, TerminalAuthError>;

    /// Fetches the user associated with an existing native bearer token.
    ///
    /// # Errors
    ///
    /// Returns an error when the token is rejected, the control-plane request
    /// fails, or the response body cannot be decoded.
    fn native_me(&self, token: &str) -> Result<MeResponse, TerminalAuthError>;

    /// Revokes an existing native bearer token.
    ///
    /// # Errors
    ///
    /// Returns an error when the token is rejected, the control-plane request
    /// fails, or the response body cannot be decoded.
    fn native_logout(&self, token: &str) -> Result<LogoutResponse, TerminalAuthError>;
}

/// `reqwest` implementation of [`ControlPlaneAuthClient`].
pub struct ReqwestControlPlaneAuthClient {
    client: Client,
    terminal_start_url: Url,
    terminal_poll_url: Url,
    terminal_exchange_url: Url,
    native_me_url: Url,
    native_logout_url: Url,
}

/// Request body for creating a terminal login attempt.
#[derive(Serialize)]
pub struct TerminalStartRequest {
    /// OAuth state value generated by the CLI.
    pub state: String,
    /// PKCE S256 challenge generated from the local verifier.
    pub code_challenge: String,
}

/// Response body returned after creating a terminal login attempt.
#[derive(Deserialize)]
pub struct TerminalStartResponse {
    /// Control-plane login attempt identifier.
    pub attempt_id: Uuid,
    /// Opaque polling secret for this attempt.
    pub poll_token: String,
    /// Browser URL the user opens to complete SSO.
    pub verification_url: String,
    /// Expiration timestamp for this login attempt.
    pub expires_at: DateTime<Utc>,
    /// Server-recommended polling interval.
    pub poll_interval_seconds: u64,
}

/// Request body for polling a terminal login attempt.
#[derive(Serialize)]
pub struct TerminalPollRequest {
    /// Control-plane login attempt identifier.
    pub attempt_id: Uuid,
    /// Opaque polling secret for this attempt.
    pub poll_token: String,
}

/// Request body for exchanging a completed terminal login attempt.
#[derive(Serialize)]
pub struct TerminalExchangeRequest {
    /// Control-plane login attempt identifier.
    pub attempt_id: Uuid,
    /// Opaque polling secret for this attempt.
    pub poll_token: String,
    /// OAuth state value originally sent to the control plane.
    pub state: String,
    /// PKCE verifier retained by the CLI.
    pub code_verifier: String,
}

/// Poll result for a terminal login attempt.
#[derive(Deserialize)]
#[non_exhaustive]
#[serde(tag = "status", rename_all = "snake_case")]
pub enum TerminalPollResponse {
    /// Browser SSO has not completed yet.
    Pending,
    /// Browser SSO completed and the attempt can be exchanged once.
    Completed,
}

/// Response body returned after exchanging a completed terminal login attempt.
#[derive(Deserialize)]
pub struct TerminalExchangeResponse {
    /// Native bearer token used by command-line clients.
    pub token: String,
    /// Expiration timestamp for the bearer token.
    pub expires_at: DateTime<Utc>,
    /// Authenticated user metadata.
    pub user: AuthenticatedUser,
}

/// Response body for the native-token `me` endpoint.
#[derive(Deserialize)]
pub struct MeResponse {
    /// Authenticated user metadata.
    pub user: AuthenticatedUser,
}

/// Response body for the native-token logout endpoint.
#[derive(Deserialize)]
pub struct LogoutResponse {
    /// Whether logout completed successfully.
    pub ok: bool,
}

impl ReqwestControlPlaneAuthClient {
    /// Builds a client for a control-plane base URL.
    ///
    /// # Errors
    ///
    /// Returns an error when the base URL cannot be combined with the expected
    /// authentication endpoint paths, or when the HTTP client cannot be built.
    pub fn new(control_plane: &str) -> Result<Self, TerminalAuthError> {
        let client = Client::builder()
            .build()
            .map_err(TerminalAuthError::ControlPlaneRequest)?;
        Ok(Self {
            client,
            terminal_start_url: endpoint_url(control_plane, TERMINAL_START_PATH)?,
            terminal_poll_url: endpoint_url(control_plane, TERMINAL_POLL_PATH)?,
            terminal_exchange_url: endpoint_url(control_plane, TERMINAL_EXCHANGE_PATH)?,
            native_me_url: endpoint_url(control_plane, NATIVE_ME_PATH)?,
            native_logout_url: endpoint_url(control_plane, NATIVE_LOGOUT_PATH)?,
        })
    }
}

impl ControlPlaneAuthClient for ReqwestControlPlaneAuthClient {
    fn start_terminal_login(
        &self,
        request: &TerminalStartRequest,
    ) -> Result<TerminalStartResponse, TerminalAuthError> {
        decode_json(
            self.client
                .post(self.terminal_start_url.clone())
                .json(request)
                .send()?,
        )
    }

    fn poll_terminal_login(
        &self,
        request: &TerminalPollRequest,
    ) -> Result<TerminalPollResponse, TerminalAuthError> {
        decode_json(
            self.client
                .post(self.terminal_poll_url.clone())
                .json(request)
                .send()?,
        )
    }

    fn exchange_terminal_login(
        &self,
        request: &TerminalExchangeRequest,
    ) -> Result<TerminalExchangeResponse, TerminalAuthError> {
        decode_json(
            self.client
                .post(self.terminal_exchange_url.clone())
                .json(request)
                .send()?,
        )
    }

    fn native_me(&self, token: &str) -> Result<MeResponse, TerminalAuthError> {
        decode_json(
            self.client
                .get(self.native_me_url.clone())
                .bearer_auth(token)
                .send()?,
        )
    }

    fn native_logout(&self, token: &str) -> Result<LogoutResponse, TerminalAuthError> {
        decode_json(
            self.client
                .post(self.native_logout_url.clone())
                .bearer_auth(token)
                .send()?,
        )
    }
}

impl From<reqwest::Error> for TerminalAuthError {
    fn from(value: reqwest::Error) -> Self {
        Self::ControlPlaneRequest(value)
    }
}

fn decode_json<T>(response: reqwest::blocking::Response) -> Result<T, TerminalAuthError>
where
    T: DeserializeOwned,
{
    let status = response.status();
    if !status.is_success() {
        let body = response
            .text()
            .unwrap_or_else(|error| format!("<failed to read body: {error}>"));
        return Err(TerminalAuthError::ControlPlaneStatus { status, body });
    }
    response
        .json()
        .map_err(TerminalAuthError::ControlPlaneRequest)
}

fn endpoint_url(control_plane: &str, path: &str) -> Result<Url, TerminalAuthError> {
    let trimmed_base = control_plane.trim_end_matches('/');
    let trimmed_path = path.trim_start_matches('/');
    let candidate = format!("{trimmed_base}/{trimmed_path}");
    Url::parse(&candidate).map_err(|source| TerminalAuthError::InvalidControlPlaneUrl {
        url: candidate,
        reason: source.to_string(),
    })
}

#[cfg(test)]
mod tests {
    use super::endpoint_url;

    #[test]
    fn endpoint_url_preserves_base_path() {
        let url = endpoint_url("http://127.0.0.1:5173/api/", "/auth/terminal/start")
            .expect("URL should parse");

        assert_eq!(
            url.as_str(),
            "http://127.0.0.1:5173/api/auth/terminal/start",
            "path-bearing control plane bases should be preserved"
        );
    }

    #[test]
    fn endpoint_url_supports_backend_origin() {
        let url =
            endpoint_url("http://127.0.0.1:8080", "auth/native/me").expect("URL should parse");

        assert_eq!(
            url.as_str(),
            "http://127.0.0.1:8080/auth/native/me",
            "backend origins should receive the endpoint path"
        );
    }
}
